<?php

if(!defined("SPR_INCLUDE")){
  header("Location: ../index.php");
}

$texty_tab['subs_temat']="Informator:";
$texty_tab['subs_domyslny']="dodefault text";
$texty_tab['subs_typy1']="Basic email group";

$texty_tab['subs_podany1']="Given email";
$texty_tab['subs_podany2']=" has been added to the subscription list";
$texty_tab['subs_zapisz_e1']="This email has been generated by";
$texty_tab['subs_zapisz_e2']="To activate newsletter subscription ( email:";
$texty_tab['subs_zapisz_e3']=") simply click on the link below";
$texty_tab['subs_zapisz_et']="activation of newsletter subscription";
$texty_tab['subs_zapisz_aby']="To activate newsletter subscription please follow the instruction sent to the given email address";
$texty_tab['subs_zapisz_nie']="Email has not been saved";
$texty_tab['subs_zapisz_istnieje']="Given email";
$texty_tab['subs_zapisz_istnieje2']="has already been saved or the subscription";
$texty_tab['subs_zapisz_niepr1']="Given email";
$texty_tab['subs_zapisz_niepr2']="is incorrect";
$texty_tab['subs_wypisz_e1']="This email has been generated by";
$texty_tab['subs_wypisz_e2']="To terminate the newsletter subscription ( email:";
$texty_tab['subs_wypisz_e3']=") simply click on the link below:";
$texty_tab['subs_wypisz_et']="termination of newsletter subscription";
$texty_tab['subs_wypisz_aby']="To terminate newsletter subscription please follow the instruction sent to the given email address";
$texty_tab['subs_wypisz_usu1']="Removal of email";
$texty_tab['subs_wypisz_usu2']="from the subscription list has been executed";
$texty_tab['subs_potw']="Thank you for confirmation, your account is already active";
$texty_tab['subs_potw_log']="subscription confirmation:";
$texty_tab['subs_potw_log']="Error - account does not exist or has been disactivated!";
$texty_tab['subs_potwu']="Your email has been removed";
$texty_tab['subs_potwu_log']="subscription removal:";
$texty_tab['subs_potwu_blad']="Error - incorrect data";

$texty_tab['subs']="Subscription:";
$texty_tab['subs_podajemail']="please give your email address:";
$texty_tab['subs_zapisz']="save";
$texty_tab['subs_wypisz']="resign";
$texty_tab['subs_wyslij']="send";


?>